allow more than one effect

diff --git a/nowplaying b/nowplaying
--- a/nowplaying
+++ b/nowplaying
@@ -23,24 +23,29 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 
+# shellcheck disable=2034
+
 export LC_ALL=C
 
 ## Global Variables
-prgnam="nowplaying.sh"
-version="1.10"
+prgnam="nowplaying"
+version="1.11"
 
+## Optional command-line variables
 plex_host="127.0.0.1"           # Plex server IP(s), separated by space
 max_width="0"                   # Set the maximum width of print; 0=infinite
-dot_leader="."                  # Delimiter used for dot leader.
-hw_transcode_symbol="•"         # Symbol to show hardware transcode
-sw_transcode_symbol="◦"         # Symbol to show software transcode
+dot_leader="."                  # Delimiter used for dot leader
+color=""                        # Toggle color output--default is "auto"
+verbose=""                      # Chatty version
 dl_agent=""                     # Either curl, wget, or fetch
 skip_checks=""                  # Skip dependency checks
 plex_file=""                    # Optional XML for testing
 plex_token=""                   # Auth token for Plex
-plexml=""                       # Holds the retrieved Plex XML Status
-color=""                        # Toggle color output--default is "auto"
-verbose=""                      # Chatty version
+
+## 
+hw_transcode_symbol="•"         # Symbol to show hardware transcode
+sw_transcode_symbol="◦"         # Symbol to show software transcode
+plexml=""                       # The active Plex XML Status
 
 ## Text Color Definitions
 black="\033[30m"
@@ -52,15 +57,16 @@ magenta="\033[35m"
 cyan="\033[36m"
 white="\033[37m"
  
-# ## Text Effect Definitions
-treset="\033[m"
+## Text Effect Definitions
 bold="\033[1m"
 italic="\033[3m"
 underline="\033[4m"
 
+# Reset text colors/effects
+treset="\033[m"
+
 ## Color Output Options
 ## todo: perhaps a config file for these?
-
 movie_color="$blue"
 episode_color="$cyan"
 song_color="$magenta"
@@ -74,7 +80,7 @@ $prgnam, version $version
 a simple, POSIX-compliant script to print the "Now Playing" status
 of a Plex server to stdout.
 
-Example: '"$prgnam" -p 192.168.1.1 -w 80 -d "." -t <PLEX_AUTH_TOKEN>
+Example: 'nowplaying -p 192.168.1.1 -w 80 -d "." -t <PLEX_AUTH_TOKEN>
          
         --plex, -p    IP address(es) or domain name of Plex Server
                       separated by commas, no spaces.
@@ -92,7 +98,7 @@ Example: '"$prgnam" -p 192.168.1.1 -w 80 -d "." -t <PLEX_AUTH_TOKEN>
 
       --version, -v   Show version
 
-      --curl <path>   Force curl as downloader.b
+      --curl <path>   Force curl as downloader.
                       (Path is optional.)
 
       --wget <path>   Force wget as downloader.
@@ -127,20 +133,15 @@ dependency_check() {
         fi
     fi
 
-    if [ -x "$(command -v curl)" ]; then
-        dl_agent="$(command -v curl)"
+    for __dla in curl wget fetch; do
+        if [ -x "$(command -v "$__dla")" ]; then
+        dl_agent="$(command -v "$__dla")"
         return 0
-    elif [ -x "$(command -v wget)" ]; then
-        dl_agent="$(command -v wget)"
-        return 0
-    elif [ -x "$(command -v fetch)" ]; then
-        dl_agent="$(command -v fetch)"
-        return 0
-    else
-        printf "Error: curl, wget, or fetch not found.\n"
-        exit 1
-    fi
-
+        fi
+    done
+    
+    printf "Error: curl, wget, or fetch not found.\n"
+    exit 1
 }
 
 color_check() {
@@ -159,15 +160,23 @@ color_check() {
     esac
 }
 
-set_color() {
+set_color() { # Usage: set_color "string" "$color" "$effect" "$effect"
     __item="$1"
     __color="$2"
-    __effect="$3"
-    if [ -n "$3" ]; then
-        printf "%b%b%s%b" "$__effect" "$__color" "$__item" "$treset"
-    else
+    __fx1="$3"
+    __fx2="$4"
+    if [ -n "$__fx2" ]; then
+        printf "%b%b%b%s%b" "$__fx1" "$__fx2" "$__color" "$__item" "$treset"
+        return
+    elif [ -n "$__fx1" ]; then
+        printf "%b%b%s%b" "$__fx1" "$__color" "$__item" "$treset"
+        return
+    elif [ -n "$__color" ]; then
         printf "%b%s%b" "$__color" "$__item" "$treset"
+        return
     fi
+    # Don't error-out if args aren't passed
+    printf "%s" "$__item"
 }
 
 get_item() {
@@ -411,6 +420,7 @@ parse_plexml() {
     __type=""
     __transcode=""
 
+    __welcome_msg="Now Playing on Plex: "
     __transcode_symbol=""
     __trans_type=""
     __count=0
@@ -443,11 +453,10 @@ parse_plexml() {
                 if [ "$__count" -eq 0 ]; then
                     printf "\n"
                     if color_check; then
-                        printf "%bNow Playing on Plex:%b\n" \
-                            "$bold" "$treset"
-                    else
-                        printf "Now playing on Plex:\n"
+                        __welcome_msg="$(set_color \
+                            "$__welcome_msg" "$white" "$italic" "$bold")"
                     fi
+                        printf "%s\n" "$__welcome_msg"
                     __count="$((__count+1))"
                 fi
 
